#!/usr/bin/env bash
# links shared agent config (rules, skills, hooks) into the config dirs of
# claude code, codex, and copilot. idempotent, re-run after adding rules.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES="$(dirname "$SCRIPT_DIR")"
AGENTS_DIR="$DOTFILES/.agents"

# codex and copilot want a single instructions file, so build one from rules/
{
  echo "<!-- generated by link-agents.sh from rules/, edit those files instead -->"
  for f in "$AGENTS_DIR"/rules/*.md; do
    echo
    cat "$f"
  done
} > "$AGENTS_DIR/AGENTS.md"
echo "generated AGENTS.md from rules/"

link() {
  local target=$1 dest=$2
  mkdir -p "$(dirname "$dest")"
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    mv "$dest" "$dest.bak.$(date +%s)"
    echo "backed up $dest"
  fi
  ln -sfn "$target" "$dest"
  echo "linked $dest -> $target"
}

# codex discovers user skills at ~/.agents/skills natively
link "$AGENTS_DIR" "$HOME/.agents"

# claude code
link "$AGENTS_DIR/rules" "$HOME/.claude/rules"
link "$AGENTS_DIR/skills" "$HOME/.claude/skills"
link "$AGENTS_DIR/agents/claude" "$HOME/.claude/agents"
link "$AGENTS_DIR/commands" "$HOME/.claude/commands"
link "$DOTFILES/.claude/settings.json" "$HOME/.claude/settings.json"

# codex
link "$AGENTS_DIR/AGENTS.md" "$HOME/.codex/AGENTS.md"
[ -f "$AGENTS_DIR/hooks/codex.json" ] && link "$AGENTS_DIR/hooks/codex.json" "$HOME/.codex/hooks.json"

# copilot
link "$AGENTS_DIR/AGENTS.md" "$HOME/.copilot/copilot-instructions.md"
link "$AGENTS_DIR/skills" "$HOME/.copilot/skills"
link "$AGENTS_DIR/agents/copilot" "$HOME/.copilot/agents"
link "$AGENTS_DIR/hooks/copilot" "$HOME/.copilot/hooks"

echo "done"
